name: release

on: 
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup go
        uses: https://github.com/actions/setup-go@v4
        with:
          go-version: '>=1.20.1'
      - name: release-build
        run: go build -ldflags="-s -w -X 'main.Version=${DRONE_TAG}'" -o bin/reverse-${DRONE_TAG}-linux-amd64
      - name: release-build-windows
        run: GOOS=windows GOARCH=amd64 go build -ldflags="-s -w -X 'main.Version=${DRONE_TAG}'" -o bin/reverse-${DRONE_TAG}-windows-amd64.exe
      - name: release-build-darwin
        run: GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w -X 'main.Version=${DRONE_TAG}'" -o bin/reverse-${DRONE_TAG}-darwin-amd64
      - name: Use Go Action  
        id: use-go-action
        uses: actions/release-action@main
        with:
          files: |-
            bin/**
          api_key: '${{secrets.RELEASE_TOKEN}}'
